/* empty css                      */import{b as l}from"./assets/vendor-CAXQE2hQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();//! =================================== Перетворення у JSON: ===================================
let s={name:"",email:"",number:""};const i=document.querySelector(".user-form");document.querySelector(".name");document.querySelector(".email");document.querySelector(".age");const u=document.querySelector(".user-form-download"),m=()=>{const o=JSON.parse(localStorage.getItem("userInfo"));if(o!==null){s=o;for(let t in s)i.elements[t].value=s[t]}};m();const f=o=>{const t=o.target.name,n=o.target.value;s[t]=n,localStorage.setItem("userInfo",JSON.stringify(s))};i.addEventListener("input",f);const d=o=>{o.preventDefault();const t=JSON.parse(localStorage.getItem("userInfo"));t.name.trim()!==""&&t.email.trim()!==""&&Number(t.number)>0?(localStorage.setItem("approovedUserInfo",JSON.stringify(t)),localStorage.removeItem("userInfo"),i.reset(),alert("Your form is succesfully sended!")):alert("Please fill form!")};i.addEventListener("submit",d);u.addEventListener("click",o=>{if(localStorage.getItem("approovedUserInfo")){const t=JSON.parse(localStorage.getItem("approovedUserInfo")),{name:n,email:a,number:e}=t;l.create(`
            <div class="modal">
                <img src="https://image.shutterstock.com/image-vector/default-avatar-profile-icon-vector-250nw-2340767883.jpg" alt="">
                <p>Name: ${n}</p>
                <p>Email: ${a}</p>
                <p>Age: ${e}</p>
            </div>
        `,{}).show()}});
//# sourceMappingURL=task-1.js.map
